CREATE TABLE TABLE_PEOPLE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    AGE INT NOT NULL CHECK (AGE > 0)
);

CREATE TABLE TABLE_CLIENTS (
    ID BIGINT PRIMARY KEY,
    CLIENT_CODE VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT FK_CLIENT_PERSON FOREIGN KEY (ID) REFERENCES TABLE_PEOPLE(ID) ON DELETE CASCADE
);

CREATE TABLE TABLE_USERS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(20) NOT NULL DEFAULT 'USER',
    ENABLED BOOLEAN DEFAULT TRUE
);
